const { comparisonFixture } = require('../../test-support/comparison-fixture')
let React, renderToStaticMarkup, Results, Content, Preparation, calculateComparison, comparisonRows, reducer, initial, snapshot
vi.mock('../../../../frontend/src/features/analytics/components/HotspotMap.jsx', () => ({ default: () => null }))
beforeAll(async () => {
  React = await import('../../../../frontend/node_modules/react/index.js')
  vi.stubGlobal('React', React)
  ;({ renderToStaticMarkup } = await import('../../../../frontend/node_modules/react-dom/server.node.js'))
  ;({ default: Results } = await import('../../../../frontend/src/features/analytics/pages/AnalysisResultsPage.jsx'))
  ;({ ReportContent: Content } = await import('../../../../frontend/src/features/analytics/components/ReportContent.jsx'))
  ;({ ReportPreparationPage: Preparation } = await import('../../../../frontend/src/features/analytics/pages/ReportPreparationPage.jsx'))
  ;({ calculateComparison, comparisonRows } = await import('../../../../frontend/src/features/analytics/lib/compareParks.js'))
  ;({ reportPreparationReducer: reducer, initialReportState: initial } = await import('../../../../frontend/src/features/analytics/lib/reportPreparation.js'))
  ;({ reportSnapshot: snapshot } = await import('../../../../frontend/src/features/analytics/lib/reportSnapshot.js'))
})
afterAll(() => vi.unstubAllGlobals())
it('groups Results and existing visualizations by park, with one report action and comparison at the end', () => {
  const html = renderToStaticMarkup(React.createElement(Results, { dataset: comparisonFixture() }))
  expect(html).toContain('Analysis for First Park')
  expect(html).toContain('Analysis for Second Park')
  expect(html.match(/View Supporting Records/g)).toHaveLength(2)
  expect(html.match(/Continue to Report</g)).toHaveLength(1)
  expect(html.match(/Incident Trends/g)).toHaveLength(2)
  expect(html.match(/Patrol Coverage/g)).toHaveLength(2)
  expect(html.indexOf('Analysis for Second Park')).toBeLessThan(html.indexOf('Comparative Overview'))
})
it('keeps all parks and findings through preparation, preview and Back without combining sources', () => {
  const dataset = comparisonFixture(), result = calculateComparison(dataset)
  let state = reducer(initial, { type: 'findings' })
  state = reducer(state, { type: 'edit', field: 'findings', value: 'Compare separately' })
  state = reducer(state, { type: 'prepare' })
  state = reducer(state, { type: 'edit', field: 'title', value: 'Park comparison' })
  const preparation = renderToStaticMarkup(React.createElement(Preparation, { state, result, dataset, dispatch: vi.fn() }))
  expect(preparation).toContain('First Park')
  expect(preparation).toContain('Second Park')
  expect(preparation).toContain('Comparative Overview')
  state = reducer(state, { type: 'generate', result, dataset, requestId: 'request' })
  expect(state.handoff.context.filters.parkIds).toEqual(dataset.filters.parkIds)
  expect(state.handoff.parks).toHaveLength(2)
  const report = { ...state.handoff, snapshot: snapshot(state.handoff) }
  const html = renderToStaticMarkup(React.createElement(Content, { report }))
  expect(html).toContain('Report for First Park')
  expect(html).toContain('Report for Second Park')
  expect(html).toContain('Compare separately')
  expect(html).toContain('Comparative Overview')
  expect(report.snapshot.parks[0].sourceReferences).toHaveLength(4)
  expect(report.snapshot.parks[1].sourceReferences).toHaveLength(2)
  expect(reducer(state, { type: 'preparation' }).findings).toBe('Compare separately')
})
it('retains empty parks and shows unavailable metrics for failed sections instead of fabricated data', () => {
  const dataset = comparisonFixture()
  dataset.datasets[1].records = { alerts: [], conflicts: [], patrolRecords: [] }
  const result = calculateComparison(dataset)
  expect(result.parks[1].status).toBe('empty')
  expect(comparisonRows(result.parks)[1]).toMatchObject({ totalEventRecords: 0, hotspots: 0, patrolHours: 0 })
  result.parks[1].analysis.hotspots = { status: 'error' }
  result.parks[1].analysis.coverage = { status: 'error' }
  expect(comparisonRows(result.parks)[1]).toMatchObject({ hotspots: null, patrolHours: null })
  const html = renderToStaticMarkup(React.createElement(Content, { report: { title: 'Empty park comparison', snapshot: snapshot(result) } }))
  expect(html).toContain('Unavailable')
  expect(html).toContain('Second Park')
})
it('blocks comparison report preparation when any park has invalid source data', () => {
  const dataset = comparisonFixture()
  dataset.datasets[1].records.alerts = null
  const html = renderToStaticMarkup(React.createElement(Results, { dataset }))
  expect(html).toContain('A park analysis could not be calculated')
  expect(html).not.toContain('Comparative Overview')
  expect(html).toMatch(/disabled=""[^>]*>Continue to Report/)
})
